// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd95AAlhlyJtxr8c79nTzHntv0acFPP-0',
    appId: '1:883197608292:web:91ad8604742105b555ba71',
    messagingSenderId: '883197608292',
    projectId: 'dancerang-733ea',
    authDomain: 'dancerang-733ea.firebaseapp.com',
    databaseURL: 'https://dancerang-733ea-default-rtdb.firebaseio.com',
    storageBucket: 'dancerang-733ea.firebasestorage.app',
    measurementId: 'G-0TLLY2DLB7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcdx0Jm51nCVkbhhxKFHLnRCLgeEejRUI',
    appId: '1:883197608292:android:b9606518fa197f4555ba71',
    messagingSenderId: '883197608292',
    projectId: 'dancerang-733ea',
    databaseURL: 'https://dancerang-733ea-default-rtdb.firebaseio.com',
    storageBucket: 'dancerang-733ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgl3U2wRplXz6Mhi7lI34NkYlKWZVsUvU',
    appId: '1:883197608292:ios:90b3fddc730730f755ba71',
    messagingSenderId: '883197608292',
    projectId: 'dancerang-733ea',
    databaseURL: 'https://dancerang-733ea-default-rtdb.firebaseio.com',
    storageBucket: 'dancerang-733ea.firebasestorage.app',
    iosBundleId: 'com.dancerang.dancerang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgl3U2wRplXz6Mhi7lI34NkYlKWZVsUvU',
    appId: '1:883197608292:ios:90b3fddc730730f755ba71',
    messagingSenderId: '883197608292',
    projectId: 'dancerang-733ea',
    databaseURL: 'https://dancerang-733ea-default-rtdb.firebaseio.com',
    storageBucket: 'dancerang-733ea.firebasestorage.app',
    iosBundleId: 'com.dancerang.dancerang',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAd95AAlhlyJtxr8c79nTzHntv0acFPP-0',
    appId: '1:883197608292:web:3a0eb27aff0179e855ba71',
    messagingSenderId: '883197608292',
    projectId: 'dancerang-733ea',
    authDomain: 'dancerang-733ea.firebaseapp.com',
    databaseURL: 'https://dancerang-733ea-default-rtdb.firebaseio.com',
    storageBucket: 'dancerang-733ea.firebasestorage.app',
    measurementId: 'G-QF1HR39BPK',
  );

}